//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataUse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public Nullable<int> task_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> task_schedule_id { get; set; }
    
        public virtual Task_Schedule Task_Schedule { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
    }
}
